# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# instruction_following_lang = the base `instruction_following` env (IFEval-style
# verifiable-instruction checking) forked with the SAME multiplicative language
# penalty + format gate used by code_gen_lang / math_with_judge_lang / stem_mcqa
# (ported from infinite-rl-nemo):
#
#     reward = if_reward * language_multiplier * format_factor
#
# where if_reward = the fraction of appended verifiable constraints the ANSWER
# satisfies (binary all-or-nothing optionally), language_multiplier enforces the
# per-row reasoning language (yue / zh-hk / en) and forbids Simplified Chinese,
# and format_factor requires a closed </think>.
#
# DUAL VERIFIER REGISTRY (the key difference vs the base env).  Our yue / zh-hk
# rows were generated by the sibling `nemo-instruction-following` project, whose
# 52 Cantonese/Written-Chinese-aware verifiers (`chinese:*`, `cantonese:*`, plus
# CJK-reimplemented `length_constraints:*` / `count:*` / `punctuation:*`) live in
# the VENDORED `cantonese_rlvr.registry` (REG) -- NVIDIA's upstream
# `verifiable_instructions` package does NOT have them.  The `en` rows come from
# the original English IFEval blend and use 9 English-only letter/case types
# (`change_case:*`, `letters:*`, `keywords:{palindrome,letter_frequency,
# no_adjacent_consecutive}`, `count:lowercase_counting`) that REG deliberately
# DROPPED -- those are graded by NVIDIA's `verifiable_instructions`.
#
# So we route by row language: `en` -> NVIDIA primary (its kwargs were authored
# for that grader), yue/zh-hk -> REG primary; each falls back to the other for
# any id the primary doesn't know.  A constraint no registry can grade (or a
# non-deterministic one that returns None, e.g. jyutping rhyme without
# pycantonese) is excluded from the denominator, exactly like the infinite-rl
# `nemo_reward._if_reward` reference.
#
# NOTE on the format check: like code_gen_lang we DROP the upstream
# reasoning-parser format penalty (our policy runs uses_reasoning_parser: false,
# so <think>...</think> stays INLINE in output_text) and use the shared
# multiplicative `format_gate` instead.  The answer is graded on the text AFTER
# </think>; the language check reads only the reasoning BEFORE </think>.

import json
import logging
import os
import threading
import time
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel

from nemo_gym.base_resources_server import (
    BaseResourcesServerConfig,
    BaseRunRequest,
    BaseVerifyRequest,
    BaseVerifyResponse,
    SimpleResourcesServer,
)
from nemo_gym.language_penalty import language_multiplier, load_sc_set

# Vendored Cantonese / Written-Chinese verifier registry (52 instruction ids).
from cantonese_rlvr import registry as R

# NVIDIA's upstream English IFEval verifiers (optional -- only needed for the 9
# English-only `en`-row instruction ids REG dropped). Guarded so the env still
# runs if the package isn't installed (those constraints then fall through to
# "unknown" and are excluded from the denominator).
try:
    from verifiable_instructions import instructions_registry as _NV_IR
except Exception:  # pragma: no cover - package optional
    _NV_IR = None

_UNKNOWN = "UNKNOWN"  # sentinel: no registry could grade this instruction id


# --------------------------------------------------------------------------- #
# Multiplicative language penalty + format gate (identical design to
# code_gen_lang / math_with_judge_lang; the reward module is shared via nemo_gym)
# --------------------------------------------------------------------------- #
class LanguagePenaltyConfig(BaseModel):
    enabled: bool = True
    sc_list_path: str  # curated simplified-only char list (SC_list.txt)
    think_tag: str = "think"
    reasoning_template: bool = False  # True if the chat template pre-opens <think>
    wrong_lang_floor: float = 0.0
    min_target_script_ratio: float = 0.15  # >= this share of alphabetic chars in the
    # target script counts as target-language (RELAXED for heavy code-mixing).
    sc_strength: float = 1.0
    sc_tolerance: float = 0.05
    sc_full_ratio: float = 0.20
    sc_floor: float = 0.0
    sc_min_hits: int = 2
    rollout_log_dir: Optional[str] = None


class FormatGateConfig(BaseModel):
    enabled: bool = True
    floor: float = 0.2
    think_tag: str = "think"


# ----------------------------
# Config
# ----------------------------
class InstructionFollowingLangResourcesServerConfig(BaseResourcesServerConfig):
    # "fraction" = passed/checked constraints (denser GRPO signal, matches the
    # infinite-rl nemo_reward reference and is preferred for this hard, multi-
    # constraint task). "binary" = 1.0 iff ALL constraints pass.
    grading_mode: Literal["binary", "fraction"] = "fraction"
    language_penalty: Optional[LanguagePenaltyConfig] = None
    format_gate: Optional[FormatGateConfig] = None


# ----------------------------
# Schemas
# ----------------------------
class InstructionFollowingLangRunRequest(BaseRunRequest):
    id: Optional[int] = None
    instruction_id_list: List[Any] = []
    prompt: Optional[str] = None
    kwargs: List[Any] = []
    # Per-row target language (yue / zh-hk / en) for the language penalty.
    language: Optional[str] = None
    grading_mode: Optional[Literal["binary", "fraction"]] = None


class InstructionFollowingLangVerifyRequest(InstructionFollowingLangRunRequest, BaseVerifyRequest):
    pass


class InstructionFollowingLangVerifyResponse(BaseVerifyResponse):
    extracted_answer: Optional[str] = None
    if_reward: float = 0.0  # fraction (or binary) of constraints satisfied
    num_constraints: int = 0  # constraints actually graded (denominator)
    num_unverifiable: int = 0  # constraints no registry could grade / returned None
    follow_instruction_list: List[Optional[bool]] = []
    instruction_id_list: List[Any] = []
    # Reward breakdown (reward = if_reward * lang_multiplier * format_factor).
    lang_multiplier: float = 1.0
    lang_factor: float = 1.0
    sc_factor: float = 1.0
    format_factor: float = 1.0


# ----------------------------
# Dual-registry verification helpers
# ----------------------------
def _reg_verify(iid: str, kw: Optional[dict], answer: str):
    """cantonese_rlvr.registry check. Returns bool | None(skip) | _UNKNOWN."""
    entry = R.REG.get(iid)
    if entry is None:
        return _UNKNOWN
    try:
        return entry["verify"](answer, kw or {})  # bool | None
    except Exception as e:  # a broken verifier must not fail the constraint silently-True
        logging.getLogger("nemo_gym").debug("REG verify error on %s: %s", iid, e)
        return False


def _nvidia_verify(iid: str, kw: Optional[dict], answer: str):
    """NVIDIA verifiable_instructions check. Returns bool | _UNKNOWN."""
    if _NV_IR is None or iid not in _NV_IR.INSTRUCTION_DICT:
        return _UNKNOWN
    try:
        inst = _NV_IR.INSTRUCTION_DICT[iid](iid)
        filt = {k: v for k, v in (kw or {}).items() if v is not None}
        inst.build_description(**filt)
        return bool(inst.check_following(answer))
    except Exception as e:  # pragma: no cover
        logging.getLogger("nemo_gym").debug("NVIDIA verify error on %s: %s", iid, e)
        return False


def _verify_one(iid: str, kw: Optional[dict], answer: str, lang: Optional[str]):
    """Route by row language; fall back to the other registry. bool|None|_UNKNOWN."""
    if lang == "en":
        order = (_nvidia_verify, _reg_verify)
    else:
        order = (_reg_verify, _nvidia_verify)
    for fn in order:
        res = fn(iid, kw, answer)
        if res is not _UNKNOWN:
            return res  # bool or None (skip)
    return _UNKNOWN


# ----------------------------
# Server
# ----------------------------
class InstructionFollowingLangResourcesServer(SimpleResourcesServer):
    config: InstructionFollowingLangResourcesServerConfig

    def model_post_init(self, context: Any) -> None:
        super().model_post_init(context)
        self._ensure_nltk_data()

        self._sc_set = frozenset()
        lp = self.config.language_penalty
        if lp is not None and lp.enabled:
            self._sc_set = load_sc_set(lp.sc_list_path)
            logging.getLogger("nemo_gym").info(
                "Language penalty ON: %d simplified chars, wrong_lang_floor=%s",
                len(self._sc_set),
                lp.wrong_lang_floor,
            )
        if _NV_IR is None:
            logging.getLogger("nemo_gym").warning(
                "verifiable_instructions not importable: the 9 English-only IFEval "
                "constraints on `en` rows will be excluded from the denominator."
            )

        self._rollout_log_path: Optional[str] = None
        self._rollout_lock = threading.Lock()
        if lp is not None and lp.enabled and lp.rollout_log_dir:
            os.makedirs(lp.rollout_log_dir, exist_ok=True)
            ts = time.strftime("%Y%m%d_%H%M%S")
            self._rollout_log_path = os.path.join(
                lp.rollout_log_dir, f"instruction_following_lang_rollouts_{ts}_{os.getpid()}.jsonl"
            )
            logging.getLogger("nemo_gym").info("Saving rollouts to %s", self._rollout_log_path)

    def _ensure_nltk_data(self):
        """NVIDIA's English word/sentence-count verifiers need NLTK punkt."""
        try:
            import nltk

            try:
                nltk.data.find("tokenizers/punkt_tab")
            except LookupError:
                nltk.download("punkt_tab", quiet=True)
        except ImportError:
            pass  # verifiable_instructions not installed; en-only path degrades gracefully
        except Exception as e:
            print(f"NLTK setup warning: {e}")

    def _log_rollout(self, record: Dict[str, Any]) -> None:
        if not self._rollout_log_path:
            return
        try:
            line = json.dumps(record, ensure_ascii=False)
            with self._rollout_lock, open(self._rollout_log_path, "a", encoding="utf-8") as f:
                f.write(line + "\n")
        except Exception:  # logging must never break verification
            logging.getLogger("nemo_gym").exception("Failed to write rollout record")

    @staticmethod
    def _extract_answer(text: str, reasoning_template: bool) -> str:
        """The answer is everything AFTER the closed </think>. With a reasoning
        template the prompt pre-opens <think>, so an unclosed rollout is pure
        (runaway) reasoning -> empty answer, and the format gate floors it."""
        if "</think>" in text:
            return text.split("</think>", 1)[1].strip()
        if reasoning_template:
            return ""
        return text.strip()

    async def verify(
        self, body: InstructionFollowingLangVerifyRequest
    ) -> InstructionFollowingLangVerifyResponse:
        model_out = body.response.output_text or ""
        text = model_out.strip()

        lp = self.config.language_penalty
        reasoning_template = bool(lp is not None and lp.reasoning_template)
        answer = self._extract_answer(text, reasoning_template)

        # ---- 1) grade each verifiable constraint -> if_reward ----
        ids = body.instruction_id_list or []
        kwargs_list = body.kwargs or []
        # pad kwargs to align with ids
        if len(kwargs_list) < len(ids):
            kwargs_list = list(kwargs_list) + [{}] * (len(ids) - len(kwargs_list))

        follow_list: List[Optional[bool]] = []
        checked = passed = unverifiable = 0
        if answer:
            for iid, kw in zip(ids, kwargs_list):
                v = _verify_one(iid, kw, answer, body.language)
                if v is _UNKNOWN or v is None:
                    follow_list.append(None)  # excluded from denominator
                    unverifiable += 1
                    continue
                follow_list.append(bool(v))
                checked += 1
                passed += 1 if v else 0
        else:
            # empty answer (or unclosed reasoning): nothing verifiable, score 0.
            follow_list = [None] * len(ids)
            unverifiable = len(ids)

        grading_mode = body.grading_mode or self.config.grading_mode
        if checked == 0:
            if_reward = 0.0
        elif grading_mode == "binary":
            if_reward = 1.0 if passed == checked else 0.0
        else:  # fraction
            if_reward = passed / checked

        reward = if_reward

        # ---- 2) multiplicative language penalty over the reasoning (< </think>) ----
        lang_mult = lang_factor = sc_factor = 1.0
        if lp is not None and lp.enabled:
            lang_mult, lang_factor, sc_factor = language_multiplier(
                text,
                body.language,
                self._sc_set,
                think_tag=lp.think_tag,
                reasoning_template=lp.reasoning_template,
                wrong_lang_floor=lp.wrong_lang_floor,
                min_target_script_ratio=lp.min_target_script_ratio,
                sc_strength=lp.sc_strength,
                sc_tolerance=lp.sc_tolerance,
                sc_full_ratio=lp.sc_full_ratio,
                sc_floor=lp.sc_floor,
                sc_min_hits=lp.sc_min_hits,
            )
            reward = reward * lang_mult

        # ---- 3) format gate: no closed </think> -> keep only `floor` of reward ----
        fg = self.config.format_gate
        think_open = reasoning_template or (f"<{fg.think_tag if fg else 'think'}>" in text)
        think_closed = f"</{fg.think_tag if fg else 'think'}>" in text
        format_factor = 1.0
        if fg is not None and fg.enabled:
            format_factor = 1.0 if f"</{fg.think_tag}>" in text else fg.floor
            reward = reward * format_factor

        self._log_rollout(
            {
                "language": body.language,
                "grading_mode": grading_mode,
                "instruction_id_list": ids,
                "if_reward": if_reward,
                "num_constraints": checked,
                "num_unverifiable": unverifiable,
                "follow_instruction_list": follow_list,
                "lang_multiplier": lang_mult,
                "lang_factor": lang_factor,
                "sc_factor": sc_factor,
                "format_factor": format_factor,
                "reward": reward,
                "think_open": think_open,
                "think_closed": think_closed,
                "answer": answer,
                "output": text,
            }
        )

        return InstructionFollowingLangVerifyResponse(
            **body.model_dump(),
            reward=float(reward),
            extracted_answer=answer,
            if_reward=if_reward,
            num_constraints=checked,
            num_unverifiable=unverifiable,
            follow_instruction_list=follow_list,
            lang_multiplier=lang_mult,
            lang_factor=lang_factor,
            sc_factor=sc_factor,
            format_factor=format_factor,
        )


if __name__ == "__main__":
    InstructionFollowingLangResourcesServer.run_webserver()
